repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.12.1  # Matches black>=23.0.0
    hooks:
    -   id: black
        language_version: python3.12

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Matches isort>=5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Matches flake8>=6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Matches mypy>=1.0.0
    hooks:
    -   id: mypy
        additional_dependencies:
        - types-requests
        - pandas-stubs
