version: '3.8'

services:
  expense-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-manager
    ports:
      - "8501:8501"
    volumes:
      # Mount data directory for persistent database storage
      - ./data:/app/data
      # Mount config directory for configuration overrides
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    networks:
      - expense-manager-network

networks:
  expense-manager-network:
    driver: bridge

volumes:
  expense-data:
    driver: local 